       SELECT OPTIONAL EMPLEADOS-ARCHIVO
       ASSIGN TO
       "C:\Users\barbu\OneDrive\Escritorio\COBOL\CursoYT\Employes27.txt"
       ORGANIZATION IS INDEXED
       RECORD KEY IS EMPLEADOS-ID
       ACCESS MODE IS DYNAMIC.
